<?xml version="1.0" encoding="UTF-8"?><testrun name="YearMonthInfractionMapperTest.testMapper" project="mapreduce" tests="1" started="1" failures="1" errors="0" ignored="0">
  <testcase name="testMapper" classname="ca.effpro.learn.hadoop.mr.tpt.exer1.YearMonthInfractionMapperTest" time="0.357">
    <failure>java.lang.AssertionError: 2 Error(s): (Missing expected output (ca.effpro.learn.hadoop.mr.tpt.exer1.YearMonthToInfractionWritable@333291e3[year=2008,month=6,infractionCode=291,dt=Sun Jun 01 00:00:00 EDT 2008], 30,ON) at position 1., Received unexpected output (ca.effpro.learn.hadoop.mr.tpt.exer1.YearMonthToInfractionWritable@479d31f3[year=2008,month=6,infractionCode=29,dt=Sun Jun 01 00:00:00 EDT 2008], 30,ON) at position 1.)
	at org.junit.Assert.fail(Assert.java:88)
	at org.apache.hadoop.mrunit.internal.util.Errors.assertNone(Errors.java:61)
	at org.apache.hadoop.mrunit.TestDriver.validate(TestDriver.java:711)
	at org.apache.hadoop.mrunit.TestDriver.runTest(TestDriver.java:575)
	at org.apache.hadoop.mrunit.TestDriver.runTest(TestDriver.java:561)
	at ca.effpro.learn.hadoop.mr.tpt.exer1.YearMonthInfractionMapperTest.testMapper(YearMonthInfractionMapperTest.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

</failure>
  </testcase>
</testrun>
